name = "UNIPACK 2"
author = "unilock"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a92dc5dabad87063bd2d7b38567da3ac3499e04a722ab9472157676afba80264"

[versions]
minecraft = "1.20.1"
quilt = "0.28.1"
unsup = "1.2.0-pre1"

[options]
acceptable-game-versions = ["1.20"]
datapack-folder = "resources/datapacks"
