name = "UNIPACK 2"
author = "unilock"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bfd13b851a87fa105a707e7d9daad44ca9997ca8fd86fde32557beb84f77b8b2"

[versions]
minecraft = "1.20.1"
quilt = "0.28.1"
unsup = "1.2.0-pre1"

[options]
acceptable-game-versions = ["1.20"]
datapack-folder = "resources/datapacks"
