name = "UNIPACK 2"
author = "unilock"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "45cee90e1f3daa213d9f0dd747dadaa5637e44fba8f97b2d71291d6d46a1085b"

[versions]
minecraft = "1.20.1"
quilt = "0.27.1"
unsup = "0.2.0"

[options]
acceptable-game-versions = ["1.20"]
datapack-folder = "resources/datapacks"
