name = "UNIPACK 2"
author = "unilock"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0181a3b65589efdcef66f7d04d4950ce3c8f38d3df586ab06483fd25f51fd8a2"

[versions]
minecraft = "1.20.1"
quilt = "0.28.1"
unsup = "1.2.0-pre1"

[options]
acceptable-game-versions = ["1.20"]
datapack-folder = "resources/datapacks"
