name = "UNIPACK 2"
author = "unilock"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "674ca410288dc232a86a78e21c53e64a1d9fc346117358b60b96e2f4f8acd954"

[versions]
minecraft = "1.20.1"
quilt = "0.29.3-beta.1"
unsup = "1.2.0-pre1"

[options]
acceptable-game-versions = ["1.20"]
datapack-folder = "resources/datapacks"
