name = "UNIPACK 2"
author = "unilock"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "17bd085b17f85e704c4e0f49fd1eb2842814ee225f3bd92a2534edbc6a793b54"

[versions]
minecraft = "1.20.1"
quilt = "0.28.1"
unsup = "1.2.0-pre1"

[options]
acceptable-game-versions = ["1.20"]
datapack-folder = "resources/datapacks"
