name = "UNIPACK 2"
author = "unilock"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b07e7fa24de44e2cf6f3151e7079a097bf2a0baf23e7dcbc95bea8669406e3d7"

[versions]
minecraft = "1.20.1"
quilt = "0.28.1"
unsup = "1.2.0-pre1"

[options]
acceptable-game-versions = ["1.20"]
datapack-folder = "resources/datapacks"
