version: 2
# Whether to use the server-side configuration.
use_server: false
sitting:
  # Controls sitting behaviour. Possible values: nothing, discard (if no block underneath sitting player), gravity.
  behaviour: "gravity"
  # Places seat in the center of the block
  should_center: false
on_use:
  # Allows to start sitting on specific blocks by interacting with them.
  sitting: true
  # Allows to start riding other players by interaction with them.
  riding: false
  # The maximum distance to a target to interact.
  range: 2
  # Prevents players from sitting in places where they would suffocate.
  check_suffocation: true
  # List of blocks or block types (e.g., "oak_log", "#logs") that are available to sit on by interacting with them.
  blocks:
  - "#minecraft:slabs"
  - "#minecraft:stairs"
on_sneak:
  # Allows to start sitting by double sneaking while looking down.
  sitting: false
  # Allows to start crawling by double sneaking near a one-block gap.
  crawling: false
  # The minimum angle must be looking down (in degrees) with double sneak.
  min_pitch: 60.0
  # The window between sneaks to sit down (in milliseconds).
  delay: 600
