#:)
prevent_tool_breaking = true
#:)
require_correct_tool_enabled = true
#:)
# Default: 64
# Range: 1 ~ 2048
block_break_limit = 64
#:)
harvest_time_per_block_modifier_enabled = false
#:)
# Default: 2.0
# Range: 1.0 ~ 10.0
harvest_time_per_block_modifier = 1.0
#:)
food_exhaustion_enabled = false
#:)
# Default: 0.2
# Range: 0.0 ~ 1.0
food_exhaustion = 0.0
